[2024-02-15 21:03:43,030] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.1.66:8000
[2024-02-15 21:03:43,030] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-02-15 21:03:48,125] 96 werkzeug - INFO - 127.0.0.1 - - [15/Feb/2024 21:03:48] "GET /predict HTTP/1.1" 200 -
[2024-02-15 21:06:34,356] 66 root - INFO - Dataframe Gathered
[2024-02-15 21:06:34,506] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/amankd777/mlops_firste/mlops_first_ever/app.py", line 32, in predict_datapoint
    return render_template("result.hmtl", final_result=result)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/amankd777/mlops_firste/mlops_first_ever/env/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: result.hmtl
[2024-02-15 21:06:34,509] 96 werkzeug - INFO - 127.0.0.1 - - [15/Feb/2024 21:06:34] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
